# Show command duration when > 2 seconds
[cmd_duration]
min_time = 2_000

# Show exit code on failure
[status]
disabled = false

[git_branch]
symbol = " "
truncation_symbol = ""

[git_state]
cherry_pick = " PICKING"

[git_status]
disabled = false

[jobs]
symbol = "✦ "
number_threshold = 1

[nodejs]
symbol = " "
style = "bold green"

[package]
symbol = " "

[python]
symbol = " "
pyenv_version_name = false

[aws]
symbol = "  "

[gcloud]
format = '[$symbol]($style) '
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[spack]
symbol = " "

[rust]
symbol = " "
